# config_N1_dynamics.yaml
# Configuration to observe patch dynamics during prolonged growth on N1

# --- Run Control & Output ---
num_steps: 1000 # Longer run to see pattern development
output_dir: "results/sample_run" # CHANGE 'X' FOR EACH PARAMETER SET BELOW
log_interval: 100 # Log/Plot snapshot every 100 steps
plot_dpi: 250
random_seed: 1234 # Use a consistent seed for comparing parameter sets initially
save_grid_data_interval: 500 # Optionally save full grid state less frequently

# --- Grid & Time Parameters ---
hex_size: 10.0
time_step_duration: 1.0

# --- Environment: Nutrient Bands ---
# Only one N1 band extending to infinity
nutrient_bands_def:
  - ["inf", N1_PREFERRED]

# --- Phenotype G (Growth-Optimized/Unprepared) Properties ---
growth_rates:
  lambda_G_N1: 0.10 # Base growth rate on N1
  # N2 parameters are irrelevant for this specific run, but keep them for dataclass structure
  alpha_G_N2: 0.01
  lag_G_N2: 25.0
  lambda_G_N2_adapted: 0.03

  # --- Phenotype P (Prepared) Properties ---
  # cost_delta_P WILL BE VARIED BELOW
  cost_delta_P: 0.01
  # N2 parameters for P are also irrelevant here
  alpha_P_N2: 0.90
  lag_P_N2: 2.0
  lambda_P_N2: 0.03

# --- Switching Rates for Bet-Hedging (probabilities per time step) ---
switching_rates:
  # G to P switch rate
  k_GP: 0.005 # Low rate to allow P to emerge slowly
  # P to G switch rate
  k_PG: 0.005 # Low rate to maintain some G presence

# --- Simulation Run Control ---
active_conflict_rule: "RANDOM_CHOICE"

# --- Initial Colony Setup ---
initial_colony_radius: 3 # Start with a slightly larger patch (19 cells)
initial_phenotype_G_fraction: 0.5 # Start mostly G, let P arise and compete
